import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <ul>
              <li>
                <a href={'/example-1-without-supressed-hydration-warning'}>
                  Example 1: Without supressed warning
                </a>
              </li>
              <li>
                <a href={'/example-2-with-supressed-hydration-warning'}>
                  Example1: With supressed warning
                </a>
              </li>
              <li>
                <a href={'/example-3-combined'}>
                  Example 3:
                  Combined
                </a>
              </li>
            </ul>
          </nav>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
